server:
  port: 8084
  servlet:
    context-path: /camunda/

# ===============================
# = CAMUNDA CONFIG
# ===============================
camunda.bpm.admin-user:
  id: demo
  password: demo
camunda:
  bpm:
    database:
      type: oracle

# ===============================
# = DATASOURCE
# ===============================
spring:
  dataSource:
    username: actio_engine_own
    password: ActioEngine
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=bdo-scan.intranet.dtgna)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=devel)))
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect